const { app, BrowserWindow, ipcMain, nativeImage } = require('electron');
const path = require('path');
const fs = require('fs');
const Store = require('./Store');
const DockAnimator = require('./DockAnimator');
const Scheduler = require('./Scheduler');
const TrayManager = require('./TrayManager');

// Keep references alive
let spriteWindow = null;
let popupWindow = null;
let dockAnimator = null;
let scheduler = null;
let trayManager = null;

app.whenReady().then(() => {
  // Hide dock while we load sprites so no blank/generic icon flashes
  app.dock.hide();

  dockAnimator = new DockAnimator(app);
  scheduler = new Scheduler(Store);

  setupIPC();

  // Start scheduler (runs independently of sprites)
  scheduler.start((event) => {
    if (event === 'reminder') {
      dockAnimator.setState('bouncing');
      trayManager && trayManager.refresh();
    } else if (event === 'notification-click') {
      showPopup('bouncing');
    } else if (event === 'tick') {
      trayManager && trayManager.refresh();
    }
  });

  // Try to load pre-generated sprites (fast path).
  // Falls back to runtime canvas generation if the files aren't present.
  const preGenerated = tryLoadPreGeneratedSprites();
  if (preGenerated) {
    onSpritesReady(preGenerated);
  } else {
    generateSpritesAtRuntime();
  }
});

// ─── Sprite loading ───────────────────────────────────────────────────────────

/**
 * Fast path: load sprites from assets/sprites/ (generated by
 * `npm run generate-sprites`).  Returns a name→dataURL map, or null if
 * the manifest / files are missing.
 */
function tryLoadPreGeneratedSprites() {
  try {
    const assetsDir = path.join(__dirname, '..', 'assets');
    const manifestPath = path.join(assetsDir, 'spritesheet.json');
    if (!fs.existsSync(manifestPath)) return null;

    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    const frames = {};

    for (const [name, info] of Object.entries(manifest)) {
      const filePath = path.join(assetsDir, info.file);
      if (!fs.existsSync(filePath)) return null; // partial assets — fall back
      const img = nativeImage.createFromPath(filePath);
      frames[name] = img.toDataURL();
    }

    return Object.keys(frames).length > 0 ? frames : null;
  } catch (e) {
    console.warn('Pre-generated sprites unavailable, falling back to runtime generation:', e.message);
    return null;
  }
}

/**
 * Slow path: spin up a hidden BrowserWindow that draws all sprite frames
 * using the HTML5 Canvas API, then sends data URLs back via IPC.
 * Used when sprite assets haven't been pre-generated.
 */
function generateSpritesAtRuntime() {
  spriteWindow = new BrowserWindow({
    width: 400,
    height: 400,
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
    },
  });

  spriteWindow.loadFile(
    path.join(__dirname, '..', 'renderer', 'sprite-generator.html')
  );
}

/** Called once we have a complete frames map (name → data URL). */
function onSpritesReady(frames) {
  dockAnimator.loadFrames(frames);
  dockAnimator.setState('sleeping');

  setupIdleTransitions();

  const trayFrame = frames['idle_1'] || frames['sleep_1'];
  trayManager = new TrayManager(Store, scheduler, () => showPopup());
  trayManager.create(trayFrame);

  app.dock.show();

  if (spriteWindow && !spriteWindow.isDestroyed()) {
    spriteWindow.close();
    spriteWindow = null;
  }
}

// ─── Popup window ─────────────────────────────────────────────────────────────

function showPopup(initialState = 'idle') {
  if (popupWindow && !popupWindow.isDestroyed()) {
    popupWindow.focus();
    popupWindow.webContents.send('animation-state', initialState);
    return;
  }

  const { screen } = require('electron');
  const { width: sw, height: sh } = screen.getPrimaryDisplay().workAreaSize;

  popupWindow = new BrowserWindow({
    width: 340,
    height: 420,
    x: sw - 360,
    y: sh - 450,
    frame: false,
    transparent: true,
    resizable: false,
    alwaysOnTop: true,
    skipTaskbar: true,
    vibrancy: 'under-window',
    visualEffectState: 'active',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
    },
  });

  popupWindow.loadFile(
    path.join(__dirname, '..', 'renderer', 'popup.html')
  );

  popupWindow.webContents.once('did-finish-load', () => {
    popupWindow.webContents.send('animation-state', initialState);
  });

  popupWindow.on('blur', () => {
    if (popupWindow && !popupWindow.isDestroyed()) popupWindow.close();
  });

  popupWindow.on('closed', () => { popupWindow = null; });

  popupWindow.show();
}

// ─── IPC handlers ─────────────────────────────────────────────────────────────

function setupIPC() {
  // Runtime sprite generation (slow path) sends frames back here
  ipcMain.on('sprites-generated', (_event, frames) => {
    onSpritesReady(frames);
  });

  ipcMain.handle('drank-water', () => {
    const streak = Store.get('streak') + 1;
    Store.set('streak', streak);
    Store.set('lastDrank', new Date().toISOString());

    dockAnimator.playOnceAndReturn('happy', 'idle');
    setTimeout(() => dockAnimator.playOnceAndReturn('celebrating', 'sleeping'), 2500);

    scheduler.resetAfterDrink();
    trayManager && trayManager.refresh();

    if (popupWindow && !popupWindow.isDestroyed()) {
      popupWindow.webContents.send('animation-state', 'happy');
      setTimeout(() => {
        if (popupWindow && !popupWindow.isDestroyed()) popupWindow.close();
      }, 3000);
    }

    return { streak };
  });

  ipcMain.handle('remind-later', () => {
    scheduler.remindLater(15);
    dockAnimator.setState('sleeping');
    trayManager && trayManager.refresh();

    if (popupWindow && !popupWindow.isDestroyed()) {
      popupWindow.webContents.send('animation-state', 'sad');
      setTimeout(() => {
        if (popupWindow && !popupWindow.isDestroyed()) popupWindow.close();
      }, 1500);
    }

    return { ok: true };
  });

  ipcMain.handle('close-popup', () => {
    if (popupWindow && !popupWindow.isDestroyed()) popupWindow.close();
    return { ok: true };
  });

  ipcMain.handle('get-streak', () => ({ streak: Store.get('streak') }));

  // No-op — runtime generator uses this path but pre-gen ignores it
  ipcMain.handle('need-sprites', () => ({ ok: true }));
}

// ─── Idle state machine ───────────────────────────────────────────────────────

let idleTimer = null;

function setupIdleTransitions() {
  function scheduleNext() {
    const delay = 20000 + Math.random() * 40000; // 20–60 s
    idleTimer = setTimeout(() => {
      const state = dockAnimator.currentState;

      if (state === 'sleeping' && Math.random() < 0.3) {
        // Occasionally wake up for a stretch, then go back to sleep
        dockAnimator.transitionTo('waking', () => {
          dockAnimator.transitionTo('idle', () => {
            setTimeout(() => {
              dockAnimator.setState('sleeping');
              scheduleNext();
            }, 5000 + Math.random() * 10000);
          });
        });
      } else if (state === 'idle') {
        dockAnimator.setState('sleeping');
        scheduleNext();
      } else {
        scheduleNext();
      }
    }, delay);
  }

  scheduleNext();
}

// ─── App lifecycle ────────────────────────────────────────────────────────────

app.on('window-all-closed', () => {
  // macOS: keep the app alive in the Dock/tray even with no open windows
});

app.on('before-quit', () => {
  dockAnimator && dockAnimator.stop();
  scheduler && scheduler.stop();
  trayManager && trayManager.destroy();
  if (idleTimer) clearTimeout(idleTimer);
});

app.on('activate', () => {
  // Dock icon clicked — show popup
  showPopup();
});
