// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pdw-popup/LayoutA.tsx": () => import("../components/mockups/pdw-popup/LayoutA.tsx"),
  "./components/mockups/pdw-popup/LayoutB.tsx": () => import("../components/mockups/pdw-popup/LayoutB.tsx"),
  "./components/mockups/pdw-popup/LayoutC.tsx": () => import("../components/mockups/pdw-popup/LayoutC.tsx"),
  "./components/mockups/pdw-popup/Popup.tsx": () => import("../components/mockups/pdw-popup/Popup.tsx")
};
